### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by shad674** [tanpatil/cse15l-lab-reports#3]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by shad674** [comment]
a description that shows what's the bug, what's the input and output, and how'd you fix it

**Comment by tanpatil** [comment]
Hey @shad674 ,
I have made the changes, please do let me know if everything is okay now
I couldn't find the 'regrade' option on gradescope, has it been made available yet?

**Comment by shad674** [comment]
yes and pls send a regrade with the links to ur issue and lab report

**Comment by shad674** [comment]
also did you change the checkmarks above?

**Comment by tanpatil** [comment]
Yeah I did, sorry was I not supposed to?

**Comment by shad674** [comment]
Yes you werent supposed to do that, you need to submit a regrade , and then we check those missing bullet points(if you did it)

**Comment by shad674** [comment]
You need to click the question that need to be regraded in order for the regrade button to work

**Comment by tanpatil** [comment]
> Yes you werent supposed to do that, you need to submit a regrade , and then we check those missing bullet points(if you did it)

Got it, sorry. I've changed it back to how it originally was.

**Comment by tanpatil** [comment]
Hey, I've sent a regrade request on gradescope, please do let me know if you've received it

**Comment by shad674** [comment]
Yup, I fixed your grade
